//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SapientServices.Data
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class RoutePlan
    {

        private System.DateTime timestampField;

        private int sensorIDField;

        private int taskIDField;

        private bool taskIDFieldSpecified;

        private int objectiveIDField;

        private bool objectiveIDFieldSpecified;

        private string routeNameField;

        private string routeDescriptionField;

        private System.DateTime etaField;

        private bool etaFieldSpecified;

        private string statusField;

        private locationList locationListField;

        private RoutePlanFieldOfView fieldOfViewField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sensorID
        {
            get
            {
                return this.sensorIDField;
            }
            set
            {
                this.sensorIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int taskID
        {
            get
            {
                return this.taskIDField;
            }
            set
            {
                this.taskIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taskIDSpecified
        {
            get
            {
                return this.taskIDFieldSpecified;
            }
            set
            {
                this.taskIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int objectiveID
        {
            get
            {
                return this.objectiveIDField;
            }
            set
            {
                this.objectiveIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool objectiveIDSpecified
        {
            get
            {
                return this.objectiveIDFieldSpecified;
            }
            set
            {
                this.objectiveIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string routeName
        {
            get
            {
                return this.routeNameField;
            }
            set
            {
                this.routeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string routeDescription
        {
            get
            {
                return this.routeDescriptionField;
            }
            set
            {
                this.routeDescriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime eta
        {
            get
            {
                return this.etaField;
            }
            set
            {
                this.etaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool etaSpecified
        {
            get
            {
                return this.etaFieldSpecified;
            }
            set
            {
                this.etaFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public locationList locationList
        {
            get
            {
                return this.locationListField;
            }
            set
            {
                this.locationListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RoutePlanFieldOfView fieldOfView
        {
            get
            {
                return this.fieldOfViewField;
            }
            set
            {
                this.fieldOfViewField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RoutePlanFieldOfView
    {

        private locationList locationListField;

        private rangeBearingCone rangeBearingConeField;

        /// <remarks/>
        public locationList locationList
        {
            get
            {
                return this.locationListField;
            }
            set
            {
                this.locationListField = value;
            }
        }

        /// <remarks/>
        public rangeBearingCone rangeBearingCone
        {
            get
            {
                return this.rangeBearingConeField;
            }
            set
            {
                this.rangeBearingConeField = value;
            }
        }
    }
}
