//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace SapientServices.Data
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class locationType
    {
        private string unitsField;

        private string datumField;

        private string zoneField;

        private string northField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string north
        {
            get
            {
                return this.northField;
            }
            set
            {
                this.northField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class settleTime
    {

        private string unitsField;

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class performanceValue
    {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class confidence
    {

        private string unitsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class subClassDefinition
    {

        private confidence confidenceField;

        private subClassDefinition[] subClassDefinition1Field;

        private int levelField;

        private string typeField;

        private string valuesField;

        /// <remarks/>
        public confidence confidence
        {
            get
            {
                return this.confidenceField;
            }
            set
            {
                this.confidenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subClassDefinition")]
        public subClassDefinition[] subClassDefinition1
        {
            get
            {
                return this.subClassDefinition1Field;
            }
            set
            {
                this.subClassDefinition1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string values
        {
            get
            {
                return this.valuesField;
            }
            set
            {
                this.valuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class filterParameter
    {

        private string nameField;

        private string operatorsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operators
        {
            get
            {
                return this.operatorsField;
            }
            set
            {
                this.operatorsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class subClassFilterDefinition
    {

        private filterParameter[] filterParameterField;

        private subClassFilterDefinition[] subClassFilterDefinition1Field;

        private int levelField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("filterParameter")]
        public filterParameter[] filterParameter
        {
            get
            {
                return this.filterParameterField;
            }
            set
            {
                this.filterParameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subClassFilterDefinition")]
        public subClassFilterDefinition[] subClassFilterDefinition1
        {
            get
            {
                return this.subClassFilterDefinition1Field;
            }
            set
            {
                this.subClassFilterDefinition1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SensorRegistration
    {

        private System.DateTime timestampField;

        private int sensorIDField;

        private bool sensorIDFieldSpecified;

        private string sensorTypeField;

        private string platformTypeField;

        private SensorRegistrationHeartbeatDefinition heartbeatDefinitionField;

        private SensorRegistrationModeDefinition[] modeDefinitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sensorID
        {
            get
            {
                return this.sensorIDField;
            }
            set
            {
                this.sensorIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sensorIDSpecified
        {
            get
            {
                return this.sensorIDFieldSpecified;
            }
            set
            {
                this.sensorIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sensorType
        {
            get
            {
                return this.sensorTypeField;
            }
            set
            {
                this.sensorTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string platformType
        {
            get
            {
                return this.platformTypeField;
            }
            set
            {
                this.platformTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationHeartbeatDefinition heartbeatDefinition
        {
            get
            {
                return this.heartbeatDefinitionField;
            }
            set
            {
                this.heartbeatDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modeDefinition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinition[] modeDefinition
        {
            get
            {
                return this.modeDefinitionField;
            }
            set
            {
                this.modeDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationHeartbeatDefinition
    {

        private SensorRegistrationHeartbeatDefinitionHeartbeatInterval heartbeatIntervalField;

        private SensorRegistrationHeartbeatDefinitionSensorLocationDefinition sensorLocationDefinitionField;

        private SensorRegistrationHeartbeatDefinitionFieldOfViewDefinition fieldOfViewDefinitionField;

        private SensorRegistrationHeartbeatDefinitionCoverageDefinition coverageDefinitionField;

        private SensorRegistrationHeartbeatDefinitionObscurationDefinition obscurationDefinitionField;

        private SensorRegistrationHeartbeatDefinitionHeartbeatReport[] heartbeatReportField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationHeartbeatDefinitionHeartbeatInterval heartbeatInterval
        {
            get
            {
                return this.heartbeatIntervalField;
            }
            set
            {
                this.heartbeatIntervalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationHeartbeatDefinitionSensorLocationDefinition sensorLocationDefinition
        {
            get
            {
                return this.sensorLocationDefinitionField;
            }
            set
            {
                this.sensorLocationDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationHeartbeatDefinitionFieldOfViewDefinition fieldOfViewDefinition
        {
            get
            {
                return this.fieldOfViewDefinitionField;
            }
            set
            {
                this.fieldOfViewDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationHeartbeatDefinitionCoverageDefinition coverageDefinition
        {
            get
            {
                return this.coverageDefinitionField;
            }
            set
            {
                this.coverageDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationHeartbeatDefinitionObscurationDefinition obscurationDefinition
        {
            get
            {
                return this.obscurationDefinitionField;
            }
            set
            {
                this.obscurationDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("heartbeatReport", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationHeartbeatDefinitionHeartbeatReport[] heartbeatReport
        {
            get
            {
                return this.heartbeatReportField;
            }
            set
            {
                this.heartbeatReportField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationHeartbeatDefinitionHeartbeatInterval
    {

        private string unitsField;

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationHeartbeatDefinitionSensorLocationDefinition
    {

        private locationType locationTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public locationType locationType
        {
            get
            {
                return this.locationTypeField;
            }
            set
            {
                this.locationTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationHeartbeatDefinitionFieldOfViewDefinition
    {

        private locationType locationTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public locationType locationType
        {
            get
            {
                return this.locationTypeField;
            }
            set
            {
                this.locationTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationHeartbeatDefinitionCoverageDefinition
    {

        private locationType locationTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public locationType locationType
        {
            get
            {
                return this.locationTypeField;
            }
            set
            {
                this.locationTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationHeartbeatDefinitionObscurationDefinition
    {

        private locationType locationTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public locationType locationType
        {
            get
            {
                return this.locationTypeField;
            }
            set
            {
                this.locationTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationHeartbeatDefinitionHeartbeatReport
    {

        private string categoryField;

        private string typeField;

        private string unitsField;

        private bool onChangeField;

        private bool onChangeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool onChange
        {
            get
            {
                return this.onChangeField;
            }
            set
            {
                this.onChangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onChangeSpecified
        {
            get
            {
                return this.onChangeFieldSpecified;
            }
            set
            {
                this.onChangeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinition
    {

        private string modeNameField;

        private string modeDescriptionField;

        private settleTime settleTimeField;

        private SensorRegistrationModeDefinitionMaximumLatency maximumLatencyField;

        private string scanTypeField;

        private string trackingTypeField;

        private SensorRegistrationModeDefinitionDuration durationField;

        private SensorRegistrationModeDefinitionModeParameter[] modeParameterField;

        private SensorRegistrationModeDefinitionDetectionDefinition detectionDefinitionField;

        private SensorRegistrationModeDefinitionTaskDefinition taskDefinitionField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modeName
        {
            get
            {
                return this.modeNameField;
            }
            set
            {
                this.modeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modeDescription
        {
            get
            {
                return this.modeDescriptionField;
            }
            set
            {
                this.modeDescriptionField = value;
            }
        }

        /// <remarks/>
        public settleTime settleTime
        {
            get
            {
                return this.settleTimeField;
            }
            set
            {
                this.settleTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionMaximumLatency maximumLatency
        {
            get
            {
                return this.maximumLatencyField;
            }
            set
            {
                this.maximumLatencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scanType
        {
            get
            {
                return this.scanTypeField;
            }
            set
            {
                this.scanTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string trackingType
        {
            get
            {
                return this.trackingTypeField;
            }
            set
            {
                this.trackingTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDuration duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("modeParameter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionModeParameter[] modeParameter
        {
            get
            {
                return this.modeParameterField;
            }
            set
            {
                this.modeParameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinition detectionDefinition
        {
            get
            {
                return this.detectionDefinitionField;
            }
            set
            {
                this.detectionDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionTaskDefinition taskDefinition
        {
            get
            {
                return this.taskDefinitionField;
            }
            set
            {
                this.taskDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionMaximumLatency
    {

        private string unitsField;

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDuration
    {

        private string unitsField;

        private int valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionModeParameter
    {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinition
    {

        private locationType locationTypeField;

        private SensorRegistrationModeDefinitionDetectionDefinitionGeometricError geometricErrorField;

        private SensorRegistrationModeDefinitionDetectionDefinitionDetectionReport[] detectionReportField;

        private SensorRegistrationModeDefinitionDetectionDefinitionDetectionPerformance[] detectionPerformanceField;

        private SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinition detectionClassDefinitionField;

        private SensorRegistrationModeDefinitionDetectionDefinitionBehaviourDefinition[] behaviourDefinitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public locationType locationType
        {
            get
            {
                return this.locationTypeField;
            }
            set
            {
                this.locationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinitionGeometricError geometricError
        {
            get
            {
                return this.geometricErrorField;
            }
            set
            {
                this.geometricErrorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detectionReport", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinitionDetectionReport[] detectionReport
        {
            get
            {
                return this.detectionReportField;
            }
            set
            {
                this.detectionReportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detectionPerformance", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinitionDetectionPerformance[] detectionPerformance
        {
            get
            {
                return this.detectionPerformanceField;
            }
            set
            {
                this.detectionPerformanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinition detectionClassDefinition
        {
            get
            {
                return this.detectionClassDefinitionField;
            }
            set
            {
                this.detectionClassDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("behaviourDefinition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinitionBehaviourDefinition[] behaviourDefinition
        {
            get
            {
                return this.behaviourDefinitionField;
            }
            set
            {
                this.behaviourDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinitionGeometricError
    {

        private performanceValue[] performanceValueField;

        private string typeField;

        private string unitsField;

        private string variationTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("performanceValue")]
        public performanceValue[] performanceValue
        {
            get
            {
                return this.performanceValueField;
            }
            set
            {
                this.performanceValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string variationType
        {
            get
            {
                return this.variationTypeField;
            }
            set
            {
                this.variationTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinitionDetectionReport
    {

        private string categoryField;

        private string typeField;

        private string unitsField;

        private bool onChangeField;

        private bool onChangeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool onChange
        {
            get
            {
                return this.onChangeField;
            }
            set
            {
                this.onChangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onChangeSpecified
        {
            get
            {
                return this.onChangeFieldSpecified;
            }
            set
            {
                this.onChangeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinitionDetectionPerformance
    {

        private performanceValue[] performanceValueField;

        private string typeField;

        private string unitsField;

        private string unitValueField;

        private string variationTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("performanceValue")]
        public performanceValue[] performanceValue
        {
            get
            {
                return this.performanceValueField;
            }
            set
            {
                this.performanceValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitValue
        {
            get
            {
                return this.unitValueField;
            }
            set
            {
                this.unitValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string variationType
        {
            get
            {
                return this.variationTypeField;
            }
            set
            {
                this.variationTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinition
    {

        private string confidenceDefinitionField;

        private SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionConfusionMatrix[] confusionMatrixField;

        private SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionClassPerformance[] classPerformanceField;

        private SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionClassDefinition[] classDefinitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string confidenceDefinition
        {
            get
            {
                return this.confidenceDefinitionField;
            }
            set
            {
                this.confidenceDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("confusionMatrix", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionConfusionMatrix[] confusionMatrix
        {
            get
            {
                return this.confusionMatrixField;
            }
            set
            {
                this.confusionMatrixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classPerformance", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionClassPerformance[] classPerformance
        {
            get
            {
                return this.classPerformanceField;
            }
            set
            {
                this.classPerformanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classDefinition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionClassDefinition[] classDefinition
        {
            get
            {
                return this.classDefinitionField;
            }
            set
            {
                this.classDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionConfusionMatrix
    {

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionClassPerformance
    {

        private performanceValue[] performanceValueField;

        private string typeField;

        private string unitsField;

        private string unitValueField;

        private string variationTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("performanceValue")]
        public performanceValue[] performanceValue
        {
            get
            {
                return this.performanceValueField;
            }
            set
            {
                this.performanceValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string unitValue
        {
            get
            {
                return this.unitValueField;
            }
            set
            {
                this.unitValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string variationType
        {
            get
            {
                return this.variationTypeField;
            }
            set
            {
                this.variationTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinitionDetectionClassDefinitionClassDefinition
    {

        private confidence confidenceField;

        private subClassDefinition[] subClassDefinitionField;

        private string typeField;

        /// <remarks/>
        public confidence confidence
        {
            get
            {
                return this.confidenceField;
            }
            set
            {
                this.confidenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subClassDefinition")]
        public subClassDefinition[] subClassDefinition
        {
            get
            {
                return this.subClassDefinitionField;
            }
            set
            {
                this.subClassDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionDetectionDefinitionBehaviourDefinition
    {

        private confidence confidenceField;

        private string typeField;

        /// <remarks/>
        public confidence confidence
        {
            get
            {
                return this.confidenceField;
            }
            set
            {
                this.confidenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionTaskDefinition
    {

        private int concurrentTasksField;

        private bool concurrentTasksFieldSpecified;

        private SensorRegistrationModeDefinitionTaskDefinitionRegionDefinition regionDefinitionField;

        private SensorRegistrationModeDefinitionTaskDefinitionCommand[] commandField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int concurrentTasks
        {
            get
            {
                return this.concurrentTasksField;
            }
            set
            {
                this.concurrentTasksField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool concurrentTasksSpecified
        {
            get
            {
                return this.concurrentTasksFieldSpecified;
            }
            set
            {
                this.concurrentTasksFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionTaskDefinitionRegionDefinition regionDefinition
        {
            get
            {
                return this.regionDefinitionField;
            }
            set
            {
                this.regionDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("command", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionTaskDefinitionCommand[] command
        {
            get
            {
                return this.commandField;
            }
            set
            {
                this.commandField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionTaskDefinitionRegionDefinition
    {

        private SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionRegionType[] regionTypeField;

        private settleTime settleTimeField;

        private locationType locationTypeField;

        private SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionClassFilterDefinition[] classFilterDefinitionField;

        private SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionBehaviourFilterDefinition[] behaviourFilterDefinitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regionType", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionRegionType[] regionType
        {
            get
            {
                return this.regionTypeField;
            }
            set
            {
                this.regionTypeField = value;
            }
        }

        /// <remarks/>
        public settleTime settleTime
        {
            get
            {
                return this.settleTimeField;
            }
            set
            {
                this.settleTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public locationType locationType
        {
            get
            {
                return this.locationTypeField;
            }
            set
            {
                this.locationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("classFilterDefinition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionClassFilterDefinition[] classFilterDefinition
        {
            get
            {
                return this.classFilterDefinitionField;
            }
            set
            {
                this.classFilterDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("behaviourFilterDefinition", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionBehaviourFilterDefinition[] behaviourFilterDefinition
        {
            get
            {
                return this.behaviourFilterDefinitionField;
            }
            set
            {
                this.behaviourFilterDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionRegionType
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionClassFilterDefinition
    {

        private filterParameter[] filterParameterField;

        private subClassFilterDefinition[] subClassFilterDefinitionField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("filterParameter")]
        public filterParameter[] filterParameter
        {
            get
            {
                return this.filterParameterField;
            }
            set
            {
                this.filterParameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subClassFilterDefinition")]
        public subClassFilterDefinition[] subClassFilterDefinition
        {
            get
            {
                return this.subClassFilterDefinitionField;
            }
            set
            {
                this.subClassFilterDefinitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionTaskDefinitionRegionDefinitionBehaviourFilterDefinition
    {

        private filterParameter[] filterParameterField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("filterParameter")]
        public filterParameter[] filterParameter
        {
            get
            {
                return this.filterParameterField;
            }
            set
            {
                this.filterParameterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SensorRegistrationModeDefinitionTaskDefinitionCommand
    {

        private string nameField;

        private string unitsField;

        private int completionTimeField;

        private string completionTimeUnitsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int completionTime
        {
            get
            {
                return this.completionTimeField;
            }
            set
            {
                this.completionTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string completionTimeUnits
        {
            get
            {
                return this.completionTimeUnitsField;
            }
            set
            {
                this.completionTimeUnitsField = value;
            }
        }
    }
}
